#!/bin/sh -e

cmd=$1
shift

AM_VERSION=-1.7

case "$cmd" in
  get-version)
        head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
    ;;
  build-exclude-list|dist-exclude-list|prepare-dist)
    ## These lists can be used to delegate build-time and dist-time exclude lists
    ## For example (syslog-ng-agent):
    ##
    ##    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user"
    ##
    ;;
  bootstrap)
    set -x
    set -e
    touch README INSTALL
    libtoolize --force --copy --install
    aclocal${AM_VERSION} -I m4
    gtkdocize --copy
    # wipe out doc generation as it does not work on all platforms
    sed -i -e 's/^install-data-local:/no-\0/' gtk-doc.make

    autoheader
    automake${AM_VERSION} --add-missing --copy  --force-missing --foreign
    autoconf --force  -i

    ;;
  configure)
    ./configure $@
    ;;
  make)
    make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0
