name: glib
builder:
  name: AutotoolsBuilder
  environments:
    NOCONFIGURE: "1"
  configure_options: "--disable-static --enable-shared --disable-gtk-doc --with-libiconv=gnu --enable-debug"
platforms:
  - linux-glibc2.11/amd64
  - ubuntu-bionic/amd64
